name: quant
channels:
  - conda-forge
  - pytorch
  - nvidia        # Added to resolve pytorch-cuda dependencies
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - xgboost
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - statsmodels
  - arch-py       # Changed from 'arch' to 'arch-py'
  - pykalman
  - jupyter
  - notebook
  - ipykernel

  - pip
  - pip:
    - yfinance
    - backtrader
    - mkdocs
    - mkdocs-material
    - mkdocs-jupyter