name: quant
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults      
dependencies:
  - python=3.11    
  - numpy<2.0       
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - xgboost
  - statsmodels
  - arch-py
  - pykalman
  - jupyter
  - notebook
  - ipykernel
  
  
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  
  

  - pip
  - pip:
    - yfinance
    - backtrader
    - mplfinance
    - mkdocs
    - mkdocs-material
    - mkdocs-jupyter